version: '3.7'


services:
  front-end:
    # build: ./front-end/front-end
    image: 192.168.0.8:5001/front-end:1.0.4
    ports:
      - "80:80"

  back-end:
    # build: ./back-end
    image: 192.168.0.8:5001/back-end:0.9
    hostname: back-end
    ports:
      - "5000:5000"
