version: '3.7'


services:
  front-end:
    build: ./front-end/front-end
    # image: front-end:0.9
    ports:
      - "80:80"

  back-end:
    build: ./back-end
    # image: back-end:0.3
    hostname: back-end
    ports:
      - "5000:5000"
