version: '3.7'

services:
  front-end:
    # build: ./front-end/front-end
    # 1.1.3
    image: 192.168.0.8:5001/front-end:1.1.6
    ports:
      - "80:80"

  back-end:
    build: ./back-end
    # image: 192.168.0.8:5001/back-end:1.0.5
    hostname: back-end
    depends_on: 
      - redis
    ports:
      - "5000:5000"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"