version: '3.7'

# networks:
#   custom_network:
#     ipam:
#       config:
#         - subnet: 172.168.0.0/16

services:
  front-end:
    # build: ./front-end/front-end
    image: 192.168.0.8:5001/front-end:1.0.7
    ports:
      - "80:80"
    # network_mode: host
    # networks:
    #   - custom_network

  back-end:
    build: .back-end
    # image: 192.168.0.8:5001/back-end:1.0.0
    hostname: back-end
    ports:
      - "5000:5000"
    # networks:
    #   - custom_network
    # network_mode: host